version: '3'

services:
  proxy:
      image: nginx:1.12
      volumes:
        - samplephpwebsite_site_v2:/var/www/html/samplephpwebsite
        - samplephpwebsite_conf_v2:/etc/nginx/conf.d/
      depends_on:
        - php71
      ports:
        - 80:80

  php71:
    image: php:7.1-fpm
    volumes:
      - samplephpwebsite_site_v2:/var/www/html/samplephpwebsite

volumes:
  samplephpwebsite_site_v2:
    external: true

  samplephpwebsite_conf_v2:
    external: true